//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkPreviewApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LinkPreviewApp.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click for Create Preview.
        /// </summary>
        internal static string Click_Create_Preview {
            get {
                return ResourceManager.GetString("Click_Create_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Preview.
        /// </summary>
        internal static string Create_Preview {
            get {
                return ResourceManager.GetString("Create_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal error occurred.
        /// </summary>
        internal static string ErrorMessage_AnInternalErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorMessage_AnInternalErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No response from service.
        /// </summary>
        internal static string ErrorMessage_NoResponseFromService {
            get {
                return ResourceManager.GetString("ErrorMessage_NoResponseFromService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recived evaluated response.
        /// </summary>
        internal static string InfoMessage_RecivedEvaluatedResponse {
            get {
                return ResourceManager.GetString("InfoMessage_RecivedEvaluatedResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending request, please wait ... .
        /// </summary>
        internal static string LoadingMessage {
            get {
                return ResourceManager.GetString("LoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview for the link:.
        /// </summary>
        internal static string PreviewForLink {
            get {
                return ResourceManager.GetString("PreviewForLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tap on the preview to go to the site.
        /// </summary>
        internal static string Tap_on_Preview {
            get {
                return ResourceManager.GetString("Tap_on_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to recognize the response from the service.
        /// </summary>
        internal static string WarningMessage_UnableRecognizeResponseFromService {
            get {
                return ResourceManager.GetString("WarningMessage_UnableRecognizeResponseFromService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a link here:.
        /// </summary>
        internal static string Write_link_here {
            get {
                return ResourceManager.GetString("Write_link_here", resourceCulture);
            }
        }
    }
}
